### PR TITLE
Change uses of 'bytes' as a variable name; bytes is a Python built-in.

### PR DESCRIPTION
**Pull request by allenap**

### CODE REVIEW

**Comment by allenap** [comment]
The term `payload` is used elsewhere to refer to the bytes explicitly forming a packet, so I've used that in most places instead of `bytes`. I've used `data` elsewhere.

**Comment by allenap** [comment]
@shylent Hi, ping, could you review this? Thanks!

**Comment by adiroiban** [comment]
Hi @allenap thanks for your PR... I was watching this.

I think that you changes are helpful.'

If you think that this project will get better visibility, I think that it would help to move it inside the GitHub Twisted organization.... we have `txacme` and `ldaptor` which are not core Twisted libraries,

**Comment by allenap** [comment]
Hi @adiroiban, that sounds like a good idea to me. This is a decent library.

However, I'm not working on the product that made use of this codebase any more, and not working with TFTP in any capacity, so it's unlikely I'll contribute here any time soon. Since @shylent seems to also be inactive, if taken into the Twisted organization this codebase would be without an obvious maintainer from the start. I guess that's the reason for adopting it though. I just wanted to make sure you knew that I'm unlikely to be a contributor.

What's the next step?

**Comment by adiroiban** [comment]
I think that the next step is to leave the project as it is and wait to see if someone else is interested.

I was planning to use TFTP and implement the window extension (https://tools.ietf.org/html/rfc7440) , but I am not currently using it.

I am monitoring all the conversations for this repo... and if there is someone else interested into contributing we can move it to Twisted so that we can at least merge the proposed changes

Have a nice day!

**Pull request closed without merging**
